server:
  port: 8889

spring:

  servlet:
    multipart:
      #      上传文件的总最大值
      max-request-size: 30MB
      #      单个文件的最大值
      max-file-size: 5MB
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-cjozdt8w.sql.tencentcdb.com:21670/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: CNTweiai1314
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #    172.17.0.2
    host: 127.0.0.1
    port: 6379
  mvc:
    servlet:
      path: /api




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_